"""add_due_date_to_tasks

Revision ID: 1c17986ce493
Revises: 8d62d630f4cb
Create Date: 2026-01-08 13:29:12.569806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1c17986ce493'
down_revision: Union[str, Sequence[str], None] = '8d62d630f4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_tasks_user_priority'), table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_user_priority'), 'tasks', ['user_id', 'priority'], unique=False)
    op.drop_column('tasks', 'due_date')
    op.alter_column('messages', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
